### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor-flow#1]
- Initialize the repo with skeleton base
- (Generated class)
- Branch protection
- Build setup (TC snapshot & release builds, release checklist)
- Add integration test.

**Comment by YuriyVaadin** [comment]
Repo initialised: https://github.com/vaadin/vaadin-rich-text-editor-flow

Needed changes for `foobar` component are applied:
 - Simple functionality
 - IT
 - Testbench element
 - Demo
 - Simple docs

`master` branch protected.

Build setup is done: https://bender.vaadin.com/project.html?projectId=VaadinProTools_RichTextEditor&tab=projectOverview

Release checklist: https://docs.google.com/spreadsheets/d/1v_VdTXFp1Bt0A777VLc5VRJkY5HXmIWereUIMm2Zn3Q/edit#gid=991259349
