### ISSUE TITLE
Improve value documentation

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-rich-text-editor-flow#10]
`getValue()`: "Returns the current value of the text editor. By default, the empty editor will return an empty string."
- This could mention something about the format being Delta. The Web Component API has a mention of this.

**Comment by web-padawan** [comment]
Also, note that the empty web component does not return an empty string.

**Comment by YuriyVaadin** [comment]
Now there are mentions about Delta format:
- https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/master/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L161 for setter
- https://github.com/vaadin/vaadin-rich-text-editor-flow/blob/master/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java#L178 for getter

There is also a ticket for switching the default value to be empty string on web component:
https://github.com/vaadin/vaadin-rich-text-editor/issues/77

**Comment by tomivirkki** [comment]
IIRC we agreed to add links to Delta. Simply stating that "Should be in Delta format" leaves the developer wondering what Delta is
