### ISSUE TITLE
How to have the editor height grow with content

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-rich-text-editor-flow#25]
Switching from `TextArea` to `RichTextEditor` I noticed that the editor height doesn't grow with content, as the former does. I don't know it is a missing feature or just a missing API to enable that, but it would be useful to have it.

**Comment by jouni** [comment]
We’d probably like to do it this way as well, but it also probably needs some extra work in IE11, so we’ve been postponing implementing it.

We could at least have this as an opt-in feature, but we’re also considering if we should have it opt-out (be the default behavior), so there wouldn’t be a need for any extra API like `<vaadin-rich-text-editor auto-height>` (or `height-by-content`).

**Comment by heruan** [comment]
asd

asd

asd

asd

**Comment by heruan** [comment]
Yeah, I suppose this is something a user would expect to be the default behavior (as it is in `TextArea`).
