### ISSUE TITLE
Setting editor in readonly mode after setting the html value makes the content text disappear from the editor

### ISSUE THREAD

**Issue by Klaudeta** [vaadin/vaadin-rich-text-editor-flow#91]
Code to reproduce the issue:
```
RichTextEditor richTextEditor = new RichTextEditor();
Button setRichTextButton = new Button("set rich value");
        setRichTextButton.addClickListener(event -> {
            richTextEditor.setReadOnly(false);
            richTextEditor.asHtml().setValue("<b>html richtext</br>test");
            richTextEditor.setReadOnly(true);
        });
add(setRichTextButton, richTextEditor);
```
The editor content does not show up at all, the component is just set in readonly mode.

**Comment by Klaudeta** [comment]
Workaround I've found for the moment is using an extended RichTextEditor and override the setReadonly method:
```
class CustomRichTextEditor extends RichTextEditor{
        @Override
        public void setReadOnly(boolean readOnly) {
            getElement()
                    .executeJs("$0.readonly="+readOnly, getElement());
        }
    }
```

**Comment by yuriy-fix** [comment]
The problem is on the webcomponent side, coming from [this line](https://github.com/vaadin/vaadin-rich-text-editor/blob/5463e92c34946e350b3d9937ddc237fd4908bb28/src/vaadin-rich-text-editor.html#L819):

`this._editor.setContents(deltaFromHtml, SOURCE.USER);`

With `SOURCE.USER` the changes are omitted in readonly mode. Changing to `SOURCE.SILENT` can fix the issue, but should be verified.

**Comment by Benjoyo** [comment]
Also having issues with this bug, please fix ASAP. This is a premium component and should receive premium support (and testing in the first place).

**Comment by thomasdewaelheyns** [comment]
I agree that for a premium component, this should have been fixed by now. More than two months without communication about this is unacceptable.

**Comment by tomivirkki** [comment]
Sorry for the delay, prioritized this in our backlog
